services:
  web_info:
    image: nginx:1.27-alpine
    container_name: web_info
    volumes:
      - ./information:/usr/share/nginx/html:ro
      - ./docker/web_info/default.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"
    networks:
      - app_net

networks:
  app_net:
    external: true
    name: app_net